---

- name: PRELIM | Capture tmp mount type | discover mount tmp type
  when:
      - ubtu22cis_rule_1_1_2_1 or
        ubtu22cis_rule_1_1_2_2 or
        ubtu22cis_rule_1_1_2_3 or
        ubtu22cis_rule_1_1_2_4
  block:
      - name: PRELIM | Capture tmp mount type | discover mount tmp type
        ansible.builtin.shell: systemctl is-enabled tmp.mount
        register: tmp_mnt_type
        changed_when: false
        failed_when: tmp_mnt_type.rc not in [ 0, 1 ]

      - name: PRELIM | Capture tmp mount type | Set fstab
        ansible.builtin.set_fact:
            tmp_mnt_type: fstab
        when: "'generated' in tmp_mnt_type.stdout"

      - name: PRELIM | Capture tmp mount type | Set systemd service
        ansible.builtin.set_fact:
            tmp_mnt_type: tmp_systemd
        when: "'generated' not in tmp_mnt_type.stdout"

- name: "PRELIM | Run apt update"
  ansible.builtin.package:
      update_cache: true
  when:
      - ubtu22cis_rule_1_3_1 or
        ubtu22cis_rule_1_9

- name: "PRELIM | Check for autofs service"
  ansible.builtin.shell: "systemctl show autofs | grep LoadState | cut -d = -f 2"
  register: ubtu22cis_autofs_service_status
  changed_when: false
  check_mode: false
  when:
      - ubtu22cis_rule_1_1_9
  tags:
      - skip_ansible_lint
      - section1

- name: "PRELIM | Check for avahi-daemon service"
  ansible.builtin.shell: "systemctl show avahi-daemon | grep LoadState | cut -d = -f 2"
  register: avahi_service_status
  changed_when: false
  check_mode: false
  when:
      - ubtu22cis_rule_2_1_3
  tags:
      - skip_ansible_lint

- name: "PRELIM | Install Network-Manager"
  ansible.builtin.package:
      name: network-manager
      state: present
  when:
      - ubtu22cis_rule_3_1_2
      - not ubtu22cis_system_is_container
      - "'network-manager' not in ansible_facts.packages"

- name: "PRELIM | Install ACL"
  ansible.builtin.package:
      name: acl
      state: present
  when:
      - ubtu22cis_rule_6_2_6
      - ubtu22cis_install_network_manager
      - "'acl' not in ansible_facts.packages"

- name: "PRELIM | Install iptables-persistent"
  ansible.builtin.package:
      name: iptables-persistent
      state: present
  when:
      - "'iptables-persistent' not in ansible_facts.packages"
      - ubtu22cis_save_iptables_cis_rules
      - ubtu22cis_firewall_package == "iptables"
      - not ubtu22cis_ipv4_required
      - ubtu22cis_rule_3_5_3_2_1 or
        ubtu22cis_rule_3_5_3_2_2 or
        ubtu22cis_rule_3_5_3_2_3 or
        ubtu22cis_rule_3_5_3_2_4 or
        ubtu22cis_rule_3_5_3_3_1 or
        ubtu22cis_rule_3_5_3_3_2 or
        ubtu22cis_rule_3_5_3_3_3 or
        ubtu22cis_rule_3_5_3_3_4

- name: "PRELIM | List users accounts"
  ansible.builtin.shell: "awk -F: '{print $1}' /etc/passwd"
  changed_when: false
  check_mode: false
  register: ubtu22cis_users
  when:
      - ubtu22cis_rule_6_2_8 or
        ubtu22cis_rule_6_2_9 or
        ubtu22cis_rule_6_2_10

- name: "PRELIM | Recapture packages"
  ansible.builtin.package_facts:
      manager: auto
