---

- name: grub update
  ansible.builtin.shell: update-grub
  failed_when: false

- name: Restart timeservice
  ansible.builtin.systemd:
    name: "{{ ubtu22cis_time_sync_tool }}"
    state: restarted

- name: Reload_systemctl
  ansible.builtin.systemd:
      daemon_reload: true

- name: Update dconf
  ansible.builtin.shell: dconf update
  failed_when: false

- name: restart postfix
  ansible.builtin.service:
      name: postfix
      state: restarted

- name: restart exim4
  ansible.builtin.service:
      name: exim4
      state: restarted

- name: sysctl flush ipv4 route table
  ansible.builtin.sysctl:
      name: net.ipv4.route.flush
      value: '1'
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: reload ufw
  ufw:
      state: reloaded

- name: iptables presistent
  ansible.builtin.shell: bash -c "iptables-save > /etc/iptables/rules.v4"
  changed_when: ubtu22cis_iptables_save.rc == 0
  failed_when: ubtu22cis_iptables_save.rc > 0
  register: ubtu22cis_iptables_save

- name: ip6tables persistent
  ansible.builtin.shell: bash -c "ip6tables-save > /etc/iptables/rules.v6"
  changed_when: ubtu22cis_ip6tables_save.rc == 0
  failed_when: ubtu22cis_ip6tables_save.rc > 0
  register: ubtu22cis_ip6tables_save

- name: sysctl flush ipv6 route table
  ansible.builtin.sysctl:
      name: net.ipv6.route.flush
      value: '1'
      sysctl_set: true
  when: ansible_virtualization_type != "docker"

- name: auditd_immutable_check
  ansible.builtin.shell: grep -c "^-e 2" /etc/audit/rules.d/99_auditd.rules
  changed_when: false
  register: auditd_immutable_check

- name: audit_immutable_fact
  ansible.builtin.debug:
      msg: "Reboot required for auditd to apply new rules as immutable set"
  notify: change_requires_reboot
  when:
      - auditd_immutable_check.stdout == '1'

- name: restart auditd
  ansible.builtin.shell: service auditd restart
  args:
      warn: false
  when:
      - audit_rules_updated.changed or
        rule_4_1_2_1.changed or
        rule_4_1_2_2.changed or
        rule_4_1_2_3.changed
  tags:
      - skip_ansible_lint

- name: remount tmp
  ansible.builtin.shell: mount -o remount /tmp

- name: restart rsyslog
  ansible.builtin.service:
      name: rsyslog
      state: restarted

- name: restart sshd
  ansible.builtin.service:
      name: sshd
      state: restarted

- name: reload gdm
  ansible.builtin.shell: dpkg-reconfigure gdm3

- name: change_requires_reboot
  ansible.builtin.set_fact:
      change_requires_reboot: true
