---

- name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var"
  block:
      - name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var | Gather /var partition"
        shell: mount | grep "on /var\s"
        changed_when: false
        failed_when: false
        check_mode: false
        args:
            warn: false
        register: ubtu22cis_1_1_3_1_var_mounted

      - name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var | Warn if /var partition does not exist"
        debug:
            msg:
                - "Warning!! There is no separate partition for /var"
                - "Please create a separate partition for /var"
        when: ubtu22cis_1_1_3_1_var_mounted.stdout | length == 0

      - name: "1.1.3.1 | AUDIT | Ensure separate partition exists for /var | Set warning count"
        set_fact:
            control_number: "{{ control_number }} + [ 'rule_1.1.3.1' ]"
            warn_count: "{{ warn_count | int + 1 }}"
        when: ubtu22cis_1_1_3_1_var_mounted.stdout | length == 0
  when:
      - ubtu22cis_rule_1_1_3_1
  tags:
      - level2-server
      - level2-workstation
      - automated
      - audit
      - rule_1.1.3.1
      - var

- name: |
    "1.1.3.2 | PATCH | Ensure /var partition includes the nodev option"
    "1.1.3.3 | PATCH | Ensure /var partition includes the nosuid option"
  mount:
      name: "{{ item.device }}"
      src: "{{ item.fstype }}"
      state: present
      fstype: xfs
      opts: defaults,{% if ubtu22cis_rule_1_1_3_2 %}nodev,{% endif %}{% if ubtu22cis_rule_1_1_3_3 %}nosuid{% endif %}
  notify: remount var
  with_items:
      - "{{ ansible_mounts }}"
  loop_control:
      label: "{{ item.device }}"
  when:
      - item.mount == "/var"
      - ubtu22cis_rule_1_1_3_2 or
        ubtu22cis_rule_1_1_3_3
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - rule_1.1.3.2
      - rule_1.1.3.3
      - var
